import {
  blogCollection,
  careerCollection,
  changelogCollection,
  companyCollection,
  contactCollection,
  faqCollection,
  featureCollection,
  homepageCollection,
  pagesCollection,
  pricingCollection,
  testimonialCollection,
} from "./types/pages.collection";
import {
  availableCountriesSectionCollection,
  benefitsSectionCollection,
  comparePlansSectionCollection,
  ctaSectionCollection,
  faqSectionCollection,
  integrationsSectionCollection,
  keyFeaturesSectionCollection,
  ourServicesSectionCollection,
  pricingSectionCollection,
  solvingProblemsSectionCollection,
  statisticsSectionCollection,
  teamMemberSectionCollection,
  testimonialSectionCollection,
  trustedBrandsSectionCollection,
} from "./types/sections.collections";

export const collections = {
  // Pages
  homepage: homepageCollection,
  blog: blogCollection,
  contact: contactCollection,
  company: companyCollection,
  feature: featureCollection,
  careers: careerCollection,
  changelog: changelogCollection,
  faq: faqCollection,
  pricing: pricingCollection,
  pages: pagesCollection,
  testimonials: testimonialCollection,

  // Sections
  trustedBrandsSectionCollection,
  ourServicesSectionCollection,
  solvingProblemsSectionCollection,
  benefitsSectionCollection,
  testimonialSectionCollection,
  teamMemberSectionCollection,
  availableCountriesSectionCollection,
  integrationsSectionCollection,
  pricingSectionCollection,
  comparePlansSectionCollection,
  keyFeaturesSectionCollection,
  statisticsSectionCollection,
  faqSectionCollection,
  ctaSectionCollection,
};
